Adds ObjectId type for the mongo connector
avct/prestgo pull request #15
Opened 2017-03-23 13:32 UTC by 0x4139

I've added a new function that converts the obtained object id to it's string representation

2017-04-06 13:32 UTC, scritchley requested changes

2017-04-06 13:32 UTC, scritchley commented on types.go
> +	ObjectId = "ObjectId"
Please add a godoc comment to this. Otherwise, this is good to merge! Thanks for your contribution.

2017-04-06 13:43 UTC, scritchley requested changes

2017-04-06 13:43 UTC, scritchley commented on conn.go
> +		} else {
This else could be removed.

2017-04-06 13:43 UTC, scritchley commented on conn.go
> +			return fmt.Sprintf("%x", data), nil
hex.EncodeToString(data) could be used here instead (it might be slightly faster)

2017-04-06 13:43 UTC, scritchley commented on conn.go
> +var objectIdConverter = valueConverterFunc(func(val interface{}) (driver.Value, error) {
Please add a test for this.

2018-01-31 10:16 UTC, ryanslade commented
Thanks, but we've decided to deprecate this library in favour of https://github.com/prestodb/presto-go-client

2018-01-31 10:16 UTC, closed without merging